spring.application.name=bookmanagment
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmanagment
spring.datasource.username=dev
spring.datasource.password=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

